//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laba
{
    using System;
    using System.Collections.Generic;
    
    public partial class Готовка_пиццы
    {
        public int ID { get; set; }
        public Nullable<int> Пицца { get; set; }
        public Nullable<int> Заказчик { get; set; }
        public Nullable<int> Пиццайоло { get; set; }
        public Nullable<int> Цена { get; set; }
    
        public virtual Заказчик Заказчик1 { get; set; }
        public virtual Пицца Пицца1 { get; set; }
        public virtual Пиццайоло Пиццайоло1 { get; set; }
    }
}
